//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthWebUI.AlarmServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AlarmServiceReference.IAlarmService")]
    public interface IAlarmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/createAlarm", ReplyAction="http://tempuri.org/IAlarmService/createAlarmResponse")]
        void createAlarm(string name, string type, string location, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/createAlarm", ReplyAction="http://tempuri.org/IAlarmService/createAlarmResponse")]
        System.Threading.Tasks.Task createAlarmAsync(string name, string type, string location, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/updateAlarm", ReplyAction="http://tempuri.org/IAlarmService/updateAlarmResponse")]
        void updateAlarm(string name, string type, string location, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/updateAlarm", ReplyAction="http://tempuri.org/IAlarmService/updateAlarmResponse")]
        System.Threading.Tasks.Task updateAlarmAsync(string name, string type, string location, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/getAlarm", ReplyAction="http://tempuri.org/IAlarmService/getAlarmResponse")]
        HealthCareWCFServices.Alarm getAlarm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/getAlarm", ReplyAction="http://tempuri.org/IAlarmService/getAlarmResponse")]
        System.Threading.Tasks.Task<HealthCareWCFServices.Alarm> getAlarmAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/getAlarms", ReplyAction="http://tempuri.org/IAlarmService/getAlarmsResponse")]
        HealthCareWCFServices.Alarm[] getAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/getAlarms", ReplyAction="http://tempuri.org/IAlarmService/getAlarmsResponse")]
        System.Threading.Tasks.Task<HealthCareWCFServices.Alarm[]> getAlarmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/deleteAlarm", ReplyAction="http://tempuri.org/IAlarmService/deleteAlarmResponse")]
        void deleteAlarm(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAlarmService/deleteAlarm", ReplyAction="http://tempuri.org/IAlarmService/deleteAlarmResponse")]
        System.Threading.Tasks.Task deleteAlarmAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlarmServiceChannel : HealthWebUI.AlarmServiceReference.IAlarmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlarmServiceClient : System.ServiceModel.ClientBase<HealthWebUI.AlarmServiceReference.IAlarmService>, HealthWebUI.AlarmServiceReference.IAlarmService {
        
        public AlarmServiceClient() {
        }
        
        public AlarmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlarmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlarmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void createAlarm(string name, string type, string location, string status) {
            base.Channel.createAlarm(name, type, location, status);
        }
        
        public System.Threading.Tasks.Task createAlarmAsync(string name, string type, string location, string status) {
            return base.Channel.createAlarmAsync(name, type, location, status);
        }
        
        public void updateAlarm(string name, string type, string location, string status) {
            base.Channel.updateAlarm(name, type, location, status);
        }
        
        public System.Threading.Tasks.Task updateAlarmAsync(string name, string type, string location, string status) {
            return base.Channel.updateAlarmAsync(name, type, location, status);
        }
        
        public HealthCareWCFServices.Alarm getAlarm(string name) {
            return base.Channel.getAlarm(name);
        }
        
        public System.Threading.Tasks.Task<HealthCareWCFServices.Alarm> getAlarmAsync(string name) {
            return base.Channel.getAlarmAsync(name);
        }
        
        public HealthCareWCFServices.Alarm[] getAlarms() {
            return base.Channel.getAlarms();
        }
        
        public System.Threading.Tasks.Task<HealthCareWCFServices.Alarm[]> getAlarmsAsync() {
            return base.Channel.getAlarmsAsync();
        }
        
        public void deleteAlarm(string name) {
            base.Channel.deleteAlarm(name);
        }
        
        public System.Threading.Tasks.Task deleteAlarmAsync(string name) {
            return base.Channel.deleteAlarmAsync(name);
        }
    }
}
