<?xml version="1.0" encoding="utf-8"?><Database Name="HealthDB" Class="HealthModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THERAK\SQLEXPRESS;Initial Catalog=HealthDB;Integrated Security=True" SettingsObjectName="HealthCareModel.Properties.Settings" SettingsPropertyName="HealthDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AlarmAttendance" Member="AlarmAttendances">
    <Type Name="AlarmAttendance">
      <Column Name="alarmId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_AlarmAttendance" Member="User" ThisKey="userId" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Alarm_AlarmAttendance" Member="Alarm" ThisKey="alarmId" OtherKey="id" Type="Alarm" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_AlarmAttendance" Member="AlarmAttendances" ThisKey="id" OtherKey="userId" Type="AlarmAttendance" />
      <Association Name="User_AssignedTask" Member="AssignedTasks" ThisKey="id" OtherKey="userId" Type="AssignedTask" />
    </Type>
  </Table>
  <Table Name="dbo.AlarmCount" Member="AlarmCounts">
    <Type Name="AlarmCount">
      <Column Name="alarmId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Alarm_AlarmCount" Member="Alarm" ThisKey="alarmId" OtherKey="id" Type="Alarm" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Alarms" Member="Alarms">
    <Type Name="Alarm">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Alarm_AlarmAttendance" Member="AlarmAttendances" ThisKey="id" OtherKey="alarmId" Type="AlarmAttendance" />
      <Association Name="Alarm_AlarmCount" Member="AlarmCount" ThisKey="id" OtherKey="alarmId" Type="AlarmCount" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.AssignedTasks" Member="AssignedTasks">
    <Type Name="AssignedTask">
      <Column Name="taskId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_AssignedTask" Member="User" ThisKey="userId" OtherKey="id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Task_AssignedTask" Member="Task" ThisKey="taskId" OtherKey="id" Type="Task" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubTasks" Member="SubTasks">
    <Type Name="SubTask">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taskId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Task_SubTask" Member="Task" ThisKey="taskId" OtherKey="id" Type="Task" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="taskName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Task_AssignedTask" Member="AssignedTasks" ThisKey="id" OtherKey="taskId" Type="AssignedTask" />
      <Association Name="Task_SubTask" Member="SubTasks" ThisKey="id" OtherKey="taskId" Type="SubTask" />
    </Type>
  </Table>
</Database>