//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthWebUI.TaskServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskServiceReference.ITaskService")]
    public interface ITaskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/createTask", ReplyAction="http://tempuri.org/ITaskService/createTaskResponse")]
        void createTask(string taskName, string status, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/createTask", ReplyAction="http://tempuri.org/ITaskService/createTaskResponse")]
        System.Threading.Tasks.Task createTaskAsync(string taskName, string status, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/updateTask", ReplyAction="http://tempuri.org/ITaskService/updateTaskResponse")]
        void updateTask(string taskName, string status, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/updateTask", ReplyAction="http://tempuri.org/ITaskService/updateTaskResponse")]
        System.Threading.Tasks.Task updateTaskAsync(string taskName, string status, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/getTask", ReplyAction="http://tempuri.org/ITaskService/getTaskResponse")]
        HealthCareWCFServices.Task getTask(string taskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/getTask", ReplyAction="http://tempuri.org/ITaskService/getTaskResponse")]
        System.Threading.Tasks.Task<HealthCareWCFServices.Task> getTaskAsync(string taskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/getTasks", ReplyAction="http://tempuri.org/ITaskService/getTasksResponse")]
        HealthCareWCFServices.Task[] getTasks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/getTasks", ReplyAction="http://tempuri.org/ITaskService/getTasksResponse")]
        System.Threading.Tasks.Task<HealthCareWCFServices.Task[]> getTasksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/deleteTask", ReplyAction="http://tempuri.org/ITaskService/deleteTaskResponse")]
        void deleteTask(string taskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/deleteTask", ReplyAction="http://tempuri.org/ITaskService/deleteTaskResponse")]
        System.Threading.Tasks.Task deleteTaskAsync(string taskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/taskStatusFilter", ReplyAction="http://tempuri.org/ITaskService/taskStatusFilterResponse")]
        HealthCareWCFServices.Task[] taskStatusFilter(string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskService/taskStatusFilter", ReplyAction="http://tempuri.org/ITaskService/taskStatusFilterResponse")]
        System.Threading.Tasks.Task<HealthCareWCFServices.Task[]> taskStatusFilterAsync(string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskServiceChannel : HealthWebUI.TaskServiceReference.ITaskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskServiceClient : System.ServiceModel.ClientBase<HealthWebUI.TaskServiceReference.ITaskService>, HealthWebUI.TaskServiceReference.ITaskService {
        
        public TaskServiceClient() {
        }
        
        public TaskServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void createTask(string taskName, string status, string description) {
            base.Channel.createTask(taskName, status, description);
        }
        
        public System.Threading.Tasks.Task createTaskAsync(string taskName, string status, string description) {
            return base.Channel.createTaskAsync(taskName, status, description);
        }
        
        public void updateTask(string taskName, string status, string description) {
            base.Channel.updateTask(taskName, status, description);
        }
        
        public System.Threading.Tasks.Task updateTaskAsync(string taskName, string status, string description) {
            return base.Channel.updateTaskAsync(taskName, status, description);
        }
        
        public HealthCareWCFServices.Task getTask(string taskName) {
            return base.Channel.getTask(taskName);
        }
        
        public System.Threading.Tasks.Task<HealthCareWCFServices.Task> getTaskAsync(string taskName) {
            return base.Channel.getTaskAsync(taskName);
        }
        
        public HealthCareWCFServices.Task[] getTasks() {
            return base.Channel.getTasks();
        }
        
        public System.Threading.Tasks.Task<HealthCareWCFServices.Task[]> getTasksAsync() {
            return base.Channel.getTasksAsync();
        }
        
        public void deleteTask(string taskName) {
            base.Channel.deleteTask(taskName);
        }
        
        public System.Threading.Tasks.Task deleteTaskAsync(string taskName) {
            return base.Channel.deleteTaskAsync(taskName);
        }
        
        public HealthCareWCFServices.Task[] taskStatusFilter(string status) {
            return base.Channel.taskStatusFilter(status);
        }
        
        public System.Threading.Tasks.Task<HealthCareWCFServices.Task[]> taskStatusFilterAsync(string status) {
            return base.Channel.taskStatusFilterAsync(status);
        }
    }
}
